# Generated by Django 5.0.9 on 2024-12-03 16:49

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(unique=True)),
                ('api_token', models.CharField()),
                ('api_url', models.URLField(unique=True)),
                ('ssl_verify', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DHCPReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC Addres like a1:b2:c3:d4:e5:f6.', regex='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$')])),
                ('status', models.CharField(default='inactive', max_length=17)),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('dhcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_dhcp.dhcpserver')),
            ],
            options={
                'ordering': ('ip_address', 'mac_address'),
            },
        ),
        migrations.AddConstraint(
            model_name='dhcpreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_address__iexact', django.db.models.functions.text.Upper('mac_address'))), fields=('mac_address',), name='unique_mac_address_case_insensitive'),
        ),
    ]
